const ADD_TO_BASKET = 'ADD_TO_BASKET'
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";
const DELETE_SELECTED_ITEMS = "DELETE_SELECTED_ITEMS";

export {ADD_TO_BASKET, REMOVE_FROM_BASKET, INCREASE_ITEM_COUNT, DECREASE_ITEM_COUNT, DELETE_SELECTED_ITEMS}